- job:
    name: networking-bgpvpn-bagpipe-dsvm-functional
    parent: legacy-dsvm-base
    run: playbooks/networking-bgpvpn-bagpipe-dsvm-functional/run.yaml
    post-run: playbooks/networking-bgpvpn-bagpipe-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-bagpipe
      - openstack/networking-bgpvpn

- job:
    name: networking-bgpvpn-bagpipe-dsvm-install
    parent: legacy-dsvm-base
    run: playbooks/networking-bgpvpn-bagpipe-dsvm-install/run.yaml
    post-run: playbooks/networking-bgpvpn-bagpipe-dsvm-install/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-bagpipe
      - openstack/networking-bgpvpn

- job:
    name: networking-bgpvpn-dsvm-functional
    parent: legacy-dsvm-base
    run: playbooks/networking-bgpvpn-dsvm-functional/run.yaml
    post-run: playbooks/networking-bgpvpn-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-bgpvpn
      - openstack/neutron
      - openstack/networking-bagpipe
      - openstack/networking-odl
      - openstack/horizon

- job:
    name: networking-bgpvpn-dsvm-install
    parent: legacy-dsvm-base
    run: playbooks/networking-bgpvpn-dsvm-install/run.yaml
    post-run: playbooks/networking-bgpvpn-dsvm-install/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-bgpvpn

- project:
    templates:
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - publish-openstack-sphinx-docs
      - release-notes-jobs
      - periodic-stable-jobs-neutron
      - check-requirements
    check:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py27:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py35:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-cover:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
        - legacy-tempest-dsvm-networking-bgpvpn-bagpipe:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - networking-bgpvpn-dsvm-functional
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py27:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py35:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-cover:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
        - legacy-tempest-dsvm-networking-bgpvpn-bagpipe:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - networking-bgpvpn-dsvm-functional
    post:
      jobs:
        - publish-openstack-python-branch-tarball:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
        - publish-openstack-sphinx-docs:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
    periodic-stable:
      jobs:
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
        - openstack-tox-py27:
            required-projects:
              - openstack/networking-odl
              - openstack/networking-bagpipe
              - openstack/horizon
    experimental:
      jobs:
        - networking-bgpvpn-dsvm-install
        - networking-bgpvpn-bagpipe-dsvm-install
        - networking-bgpvpn-bagpipe-dsvm-functional
