- job:
    name: networking-bgpvpn-bagpipe-dsvm-functional
    parent: legacy-dsvm-base
    run: playbooks/networking-bgpvpn-bagpipe-dsvm-functional/run.yaml
    post-run: playbooks/networking-bgpvpn-bagpipe-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-bagpipe
      - openstack/networking-bgpvpn

- job:
    name: networking-bgpvpn-bagpipe-dsvm-install
    parent: legacy-dsvm-base
    run: playbooks/networking-bgpvpn-bagpipe-dsvm-install/run.yaml
    post-run: playbooks/networking-bgpvpn-bagpipe-dsvm-install/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-bagpipe
      - openstack/networking-bgpvpn

- job:
    name: networking-bgpvpn-dsvm-functional
    parent: legacy-dsvm-base
    run: playbooks/networking-bgpvpn-dsvm-functional/run.yaml
    post-run: playbooks/networking-bgpvpn-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-bgpvpn
      - openstack/neutron
      - openstack/networking-bagpipe
      - openstack/networking-odl
      - openstack/horizon

- job:
    name: networking-bgpvpn-dsvm-install
    parent: legacy-dsvm-base
    run: playbooks/networking-bgpvpn-dsvm-install/run.yaml
    post-run: playbooks/networking-bgpvpn-dsvm-install/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/networking-bgpvpn

- project:
    templates:
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - publish-openstack-sphinx-docs
      - release-notes-jobs
      - periodic-stable-jobs-neutron
      - check-requirements
    check:
      jobs:
        # TripleO jobs that deploy networking-bgpvpn.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario004-multinode-oooq will only
        # run on stable/pike while the -container will run in Queens
        # and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario004-multinode-oooq:
            voting: false
        - tripleo-ci-centos-7-scenario004-multinode-oooq-container:
            voting: false
        - openstack-tox-pep8:
            required-projects:
              - openstack/networking-odl
        - openstack-tox-py27:
            required-projects:
              - openstack/networking-odl
        - openstack-tox-py35:
            required-projects:
              - openstack/networking-odl
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/networking-odl
        - openstack-tox-cover:
            required-projects:
              - openstack/networking-odl
        - legacy-tempest-dsvm-networking-bgpvpn-bagpipe:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - networking-bgpvpn-dsvm-functional
    gate:
      jobs:
        - openstack-tox-pep8:
            required-projects:
              - openstack/networking-odl
        - openstack-tox-py27:
            required-projects:
              - openstack/networking-odl
        - openstack-tox-py35:
            required-projects:
              - openstack/networking-odl
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/networking-odl
        - openstack-tox-cover:
            required-projects:
              - openstack/networking-odl
        - legacy-tempest-dsvm-networking-bgpvpn-bagpipe:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - networking-bgpvpn-dsvm-functional
    periodic-stable:
      jobs:
        - build-openstack-sphinx-docs:
            required-projects:
              - openstack/networking-odl
        - openstack-tox-py27:
            required-projects:
              - openstack/networking-odl
    experimental:
      jobs:
        - networking-bgpvpn-dsvm-install
        - networking-bgpvpn-bagpipe-dsvm-install
        - networking-bgpvpn-bagpipe-dsvm-functional
    post:
      jobs:
        - publish-openstack-python-branch-tarball:
            required-projects:
              - openstack/networking-bagpipe
              - openstack/horizon
        - publish-openstack-sphinx-docs
